version: '3.9'

services:   

  frontend:
    build: ./ml-kurkkumopo-frontend-master/
    ports:
      - 3000:3000

  backend:
    build: ./ml-kurkkumopo-backend-master/
    ports:
      - 5000:5000
    volumes:
      - ./model:/src/model 
    depends_on:
      - training

  training:
    build: ./ml-kurkkumopo-training-master/
    volumes:
        - ./model:/src/model
        - ./imgs:/src/imgs

volumes:
  model:
  imgs: