version: '3.8'

services:
  simple-web-service:
    image: devopsdockeruh/simple-web-service
    volumes:
      - ./logs.txt:/usr/src/app/text.log
    container_name: simple-web-service

    
    
    
    
#Remember to create logs.txt for it to work with 'touch logs.txt'