version: '3.9'

services:   

  db:
    image: postgres:13.2-alpine
    restart: unless-stopped
    environment:
        POSTGRES_PASSWORD: example
    volumes:
      - ./database:/var/lib/postgresql/data

  #proxy:
  #  image: nginx
  #  ports:
  #    - 80:80
  #  volumes:
  #    - ./ngnix.conf:/etc/nginx/nginx.conf:ro


  redis:
    image: redis
    
  frontend:
    build: ./frontend/
    ports:
      - 5000:5000

  backend:
    build: ./backend/
    ports:
      - 8080:8080
    environment: 
      - REDIS_HOST=redis
      - POSTGRES_USER=postgres
      - POSTGRES_HOST=db
      - POSTGRES_PASSWORD=example
    depends_on:
      - db

volumes:
    database: